package com.ecommerce.service;

import net.sf.jsqlparser.JSQLParserException;
import net.sf.jsqlparser.parser.CCJSqlParserUtil;
import net.sf.jsqlparser.statement.Statement;
import net.sf.jsqlparser.statement.Statements;
import net.sf.jsqlparser.statement.select.Select;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Service;

import java.util.List;
import java.util.Map;
import java.util.Set;

@Service
public class QueryExecutionService {

    private final JdbcTemplate aiJdbcTemplate;

    // Hardcoded blacklist of sensitive fields
    private static final Set<String> SENSITIVE_COLUMNS = Set.of(
            "password", "password_hash", "jwt_secret", "credit_card", "secret", "token"
    );

    @Autowired
    public QueryExecutionService(@Qualifier("aiJdbcTemplate") JdbcTemplate aiJdbcTemplate) {
        this.aiJdbcTemplate = aiJdbcTemplate;
    }

    /**
     * Parses, validates securely, and executes the dynamic AI SQL.
     * @param rawSql The raw SQL string generated by the AI
     * @return List of generic key-value maps representing the data rows
     */
    public List<Map<String, Object>> executeSafeQuery(String rawSql) {
        try {
            // STEP 2: AST Parsing (Pre-Execution Validation)
            // parseStatements strictly prevents multi-statement blocks 
            Statements statements = CCJSqlParserUtil.parseStatements(rawSql);
            if (statements.size() != 1) {
                throw new SecurityException("Multiple SQL statements detected. Only a single query is allowed.");
            }

            Statement statement = statements.get(0);

            // Operation Whitelist: Block UPDATE, DELETE, INSERT, DROP, ALTER
            if (!(statement instanceof Select)) {
                throw new SecurityException("Unauthorized SQL command detected. Only SELECT operations are permitted.");
            }

            Select selectStatement = (Select) statement;

            // STEP 3: Enforce Column-Level Whitelisting
            validateColumns(selectStatement);

            // STEP 4: Execute and Map the Data
            // Execute natively using the restricted AI read-only template
            return aiJdbcTemplate.queryForList(rawSql);

        } catch (JSQLParserException e) {
            // STEP 5: Catch and Sanitize Errors
            // AV-07: Never leak Java stack traces to the LLM or Client
            throw new RuntimeException("SQL Syntax Error: The query is structurally invalid. Please revise the syntax.");
        } catch (SecurityException e) {
            // Pass the clean security block reason back
            throw new RuntimeException("Security Block: " + e.getMessage());
        } catch (Exception e) {
            // Catch actual DB errors like "Table not found" cleanly
            throw new RuntimeException("Database Execution Error: Ensure the requested tables and columns exist.");
        }
    }

    private void validateColumns(Select selectStatement) {
        // Inspect the parsed AST Select body to check explicitly requested columns
        if (selectStatement instanceof net.sf.jsqlparser.statement.select.PlainSelect) {
            net.sf.jsqlparser.statement.select.PlainSelect plainSelect = 
                (net.sf.jsqlparser.statement.select.PlainSelect) selectStatement;
            
            for (Object itemObj : plainSelect.getSelectItems()) {
                String itemStr = itemObj.toString().toLowerCase();

                // Block Wildcards (AV-12 Exfiltration)
                if (itemStr.contains("*")) {
                    throw new SecurityException("SELECT * (Wildcards) are forbidden. Explicitly name columns.");
                }

                // Block Sensitive Fields
                for (String sensitive : SENSITIVE_COLUMNS) {
                    if (itemStr.contains(sensitive)) {
                        throw new SecurityException("Access to sensitive column blocked: " + sensitive);
                    }
                }
            }
        }
    }
}
